### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#106]
- [x] spell check documentation
- [x] final obs release from Factory -> 1.0
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] replace lorem ipsum wordpress post with press release
- [x] finalize changelog
- [x] upload install guide pdf to wordpress
- [x] add changelog to release

**Comment by koomie** [comment]
Hello sweetie, we're all done for this one.
