### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#175]
- [x] spell check documentation
- [x] verify correct version in docs
- [x] verify url of ohpc-release package in ohpc-docs
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version in ohpc-docs
- [x] final obs release from Factory -> Update1
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [x] upload install guide pdf to wordpress
- [x] add changelog to release
- [x] upload ohpc-release to release page and ohpc website
- [x] update .repo file download commentary on ohpc website
- [x] merge 1.0.1 branch to 1.1
- [x] post to ohpc-announce
