### ISSUE TITLE
1.1 Release Checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#206]
- [x] spell check documentation
- [x] verify correct version in docs (git sha + ohpc version)
- [x] verify url of ohpc-release package in ohpc-docs
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version in ohpc-docs
- [x] final obs release from Factory -> 1.1
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [x] upload install guide pdf to wordpress
- [x] add changelog to release
- [x] build ISO, update links in README.md
- [x] upload ohpc-release RPMs to release page 
- [x] update md5sums in README.md
- [x] update ohpc-release file download commentary on ohpc website
- [x] merge 1.1 branch to 1.1.1
- [x] make 1.1 default branch on github
- [x] post to ohpc-announce
