### ISSUE TITLE
1.1.1 Checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#227]
- [x] spell check documentation
- [x] verify correct version in docs (git sha + ohpc version)
- [x] verify url of ohpc-release package in ohpc-docs
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version in ohpc-docs
- [x] final obs release from 1.1:Update1:Factory -> 1.1:Update1
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [x] upload install guide pdf to wordpress
- [x] add changelog to release
- [x] alter [update] repo link to point to update1 release
- [x] build ISO, update links in README.md
- [x] upload ohpc-release RPMs to release page (no change from 1.1)
- [x] update md5sums in README.md (no change from 1.1)
- [x] update ohpc-release file download commentary on ohpc website
- [x] merge 1.1.1 branch to master
- [x] make 1.1.1 default branch on github
- [x] post to ohpc-announce
