### ISSUE TITLE
1.2 Release Checklist 

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#332]
- [x] spell check documentation
- [x] verify correct version in docs (git sha + ohpc version)
- [x] verify url of ohpc-release package in ohpc-docs
  - [x] centos/x86
  - [x] sles/x86
  - [x] sles/aarch
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version in ohpc-docs
- [x] final obs release from Factory -> 1.2
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [ ] upload install guide pdf to wordpress
- [x] add changelog to release
- [x] build ISO, update links in README.md
- [x] upload ohpc-release RPMs to release page 
- [x] upload install guides to release page 
- [x] update md5sums in README.md
- [x] update ohpc-release file download commentary on ohpc website
- [x] merge 1.2 branch to 1.2.1
- [x] make 1.2 default branch on github
- [x] post to ohpc-announce

**Comment by koomie** [comment]
baby steps to the elevator....
