### ISSUE TITLE
1.2.1 Release Checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#357]
- [x] spell check documentation
- [x] verify correct version in docs
   - [x] git sha
   - [x] ohpc version
- [x] verify url of ohpc-release package in ohpc-docs
  - [x] centos/x86
  - [x] sles/x86
  - [x] centos/aarch
  - [x] sles/aarch
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version of `docs-ohpc`
- [x] final obs release from Factory 
- [x] final manifest generation
- [x] disabled future builds in Factory
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [x] upload install guide pdf to wordpress
- [x] add changelog to release
- [x] build final dist tarballs, update links in README.md
- [x] upload ohpc-release RPMs to release page (no change for 1.2.1)
- [x] upload install guides to release page 
- [x] update md5sums in README.md
- [x] update ohpc-release file download commentary on ohpc website (not required for 1.2.1)
- [x] merge 1.2.1 branch to 1.2.2, 1.3, and master
- [x] make 1.2.1 default branch on github
- [x] post to ohpc-announce
- [x] alter [update] repo link to point to update1 release
