### ISSUE TITLE
1.3 Release Checklist

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#381]
- [x] spell check documentation
- [x] verify correct version in docs
   - [x] git sha
   - [x] ohpc version
- [x] verify url of ohpc-release package in ohpc-docs
  - [x] centos/x86
  - [x] sles/x86
  - [x] centos/aarch
  - [x] sles/aarch
- [x] clean up page breaks in ohpc-docs
- [x] verify rpm version of `docs-ohpc`
- [x] final obs release from Factory 
- [x] final manifest generation
- [x] disabled future builds in Factory (now using lock)
- [x] remove draft watermark
- [x] tag release
- [x] tag release for CI infrastructure 
- [x] finalize changelog
- [x] update install guide links on community site
- [x] add changelog to release
- [x] build final dist tarballs, update links in README.md
- [x] complete jenkins run with dist tarballs
- [x] upload ohpc-release RPMs to release page
- [x] upload install guides to release page 
- [x] update md5sums in README.md
- [x] update ohpc-release file download commentary on ohpc website 
- [x] merge 1.3 branch to 1.31 and master
- [x] make 1.3 default branch on github
- [x] post to ohpc-announce
- [x] alter [update] repo link to point to update1 release - N/A for minor release
